const admin = require('firebase-admin');
const cron = require('node-cron');
const fetch = require('node-fetch');

const TELEGRAM_BOT_TOKEN = '8612341123:AAGReJ5tY8q0UITugt4dUVZasskPK_H8FBk';
const TELEGRAM_CHAT_ID = '-1003726991466';

const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT || '{}');
if (serviceAccount.project_id) {
    admin.initializeApp({ credential: admin.credential.cert(serviceAccount) });
} else {
    admin.initializeApp({ projectId: 'ozisik-paketleme' });
}
const db = admin.firestore();

async function sendTelegram(message) {
    try {
        const url = `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`;
        const resp = await fetch(url, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ chat_id: TELEGRAM_CHAT_ID, text: message, parse_mode: 'HTML' })
        });
        const data = await resp.json();
        console.log(data.ok ? 'Telegram mesaji gonderildi' : 'Telegram hatasi: ' + JSON.stringify(data));
    } catch (e) { console.error('Telegram hata:', e.message); }
}

function shuffle(arr) {
    for (let i = arr.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
}

async function runAutoAssign(isTest) {
    console.log((isTest ? 'TEST ' : '') + 'Otomatik atama basliyor...');
    try {
        const doc = await db.collection('appData').doc('beyazPeynir').get();
        if (!doc.exists) { await sendTelegram('⚠️ Veri bulunamadi.'); return; }
        const S = doc.data();
        const personnel = S.personnel || [];
        const machines = S.machines || [];
        const mcfg = S.mcfg || {};
        const cleaning = S.cleaning || {};

        const today = new Date();
        const dayOfWeek = today.getDay();

        let group, groupLabel;
        if (isTest) {
            if (dayOfWeek >= 1 && dayOfWeek <= 3) {
                group = '1'; groupLabel = '1. Grup (Pzt-Sal-Çar)';
            } else {
                group = '2'; groupLabel = '2. Grup (Per-Cum-Cmt)';
            }
        } else {
            if (dayOfWeek === 3) { group = '1'; groupLabel = '1. Grup (Pzt-Sal-Çar)'; }
            else if (dayOfWeek === 6) { group = '2'; groupLabel = '2. Grup (Per-Cum-Cmt)'; }
            else { console.log('Bugun atama gunu degil.'); return; }
        }

        const mondayOffset = dayOfWeek === 0 ? -6 : 1 - dayOfWeek;
        const monday = new Date(today);
        monday.setDate(today.getDate() + mondayOffset);

        const groupDates = [];
        const gunler = ['Pazar','Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi'];
        const startOffset = group === '1' ? 0 : 3;
        for (let i = 0; i < 3; i++) {
            const d = new Date(monday);
            d.setDate(monday.getDate() + startOffset + i);
            groupDates.push(d);
        }
        const dateFrom = groupDates[0].toISOString().split('T')[0];
        const dateTo = groupDates[groupDates.length - 1].toISOString().split('T')[0];
        const groupDays = groupDates.map(d => ({ day: gunler[d.getDay()], date: d.toISOString().split('T')[0] }));

        const avail = personnel.filter(p => p.status === 'active' && !p.role && !p.fixedRole);
        const fixedPersonnel = personnel.filter(p => p.status === 'active' && p.fixedRole && !p.role);
        if (!avail.length) { await sendTelegram('⚠️ Aktif personel yok.'); return; }

        shuffle(avail);
        let idx = 0;
        const pick = (n) => { const r = []; for (let i = 0; i < n && idx < avail.length; i++) r.push(avail[idx++]); return r; };

        const assignment = {
            dateFrom, dateTo, weekStart: monday.toISOString().split('T')[0], group, groupLabel, shift: 'sabah', groupDays,
            machineAssignments: [], tasks: { dilimleme: [], tarihMakinesi: [], temizlik: [] },
            fixedRoles: fixedPersonnel.map(p => ({ id: p.id, name: p.name, role: p.fixedRole })),
            createdAt: new Date().toISOString(), autoGenerated: true
        };

        machines.forEach(m => {
            const c = mcfg[m.id] || { gramaj: 10, etiket: 1, kontrol: 1, koli: 1, makKoyma: 0 };
            const mAssign = { machineId: m.id, machineName: m.name, desks: [], makKoyma: [], etiket: [], kontrol: [], koli: [] };
            const gramajP = pick(c.gramaj);
            const desks = m.desks || [{ name: 'Sol' }, { name: 'Sağ' }];
            const deskArrays = desks.map(() => []);
            gramajP.forEach((p, i) => deskArrays[i % desks.length].push(p));
            desks.forEach((desk, i) => {
                mAssign.desks.push({ name: desk.name, persons: (deskArrays[i] || []).map(p => ({ id: p.id, name: p.name, scaleNo: null })) });
            });
            pick(c.makKoyma || 0).forEach(p => mAssign.makKoyma.push({ id: p.id, name: p.name }));
            pick(c.etiket).forEach(p => mAssign.etiket.push({ id: p.id, name: p.name }));
            pick(c.kontrol).forEach(p => mAssign.kontrol.push({ id: p.id, name: p.name }));
            pick(c.koli).forEach(p => mAssign.koli.push({ id: p.id, name: p.name }));
            gramajP.forEach(p => { p.gC = (p.gC || 0) + 1; });
            assignment.machineAssignments.push(mAssign);
        });

        if (S.dilimEnabled) pick(S.dilimCount || 2).forEach(p => assignment.tasks.dilimleme.push({ id: p.id, name: p.name }));
        if (S.tarihMakEnabled) pick(S.tarihMakCount || 1).forEach(p => assignment.tasks.tarihMakinesi.push({ id: p.id, name: p.name }));

        const CLEAN_ITEMS = [
            {id:'c1',label:'Vakum Makine İçi'},{id:'c2',label:'Vakum Makine Dışı'},{id:'c3',label:'Terazi Temizliği'},
            {id:'c4',label:'Zemin Temizliği'},{id:'c5',label:'Tartı & Bıçak Temizliği'},{id:'c6',label:'Koli Alanı'},
            {id:'c7',label:'Teneke Alanı'},{id:'c8',label:'Genel Alan'},{id:'c9',label:'Masa Temizliği'}
        ];
        const cleanPool = avail.slice(0, idx);
        let cIdx = 0;
        CLEAN_ITEMS.forEach(cItem => {
            const cfg = cleaning[cItem.id];
            if (cfg && cfg.on) {
                for (let i = 0; i < (cfg.count || 1); i++) {
                    if (cleanPool.length) {
                        const p = cleanPool[cIdx % cleanPool.length];
                        assignment.tasks.temizlik.push({ id: p.id, name: p.name, area: cItem.label, areaId: cItem.id });
                        cIdx++;
                    }
                }
            }
        });

        const history = S.history || [];
        const existingIdx = history.findIndex(h => h.dateFrom === dateFrom && h.group === group);
        if (existingIdx >= 0) history.splice(existingIdx, 1);
        history.unshift(assignment);
        await db.collection('appData').doc('beyazPeynir').update({ personnel, history, cur: assignment });

        let msg = `📋 <b>ÖZIŞIK SÜT ÜRÜNLERİ</b>\n🧀 <b>Beyaz Peynir Paketleme Atama</b>\n`;
        if (isTest) msg += `⚠️ <b>TEST MESAJI</b>\n`;
        msg += `━━━━━━━━━━━━━━━━━━━━\n`;
        msg += `📅 <b>${groupLabel}</b>\n`;
        msg += `📆 ${groupDays.map(d => d.day + ' ' + d.date.substring(5).replace('-','/')).join(' · ')}\n`;
        msg += `☀️ Sabah Vardiyası\n\n`;

        assignment.machineAssignments.forEach(ma => {
            msg += `🏭 <b>${ma.machineName}</b>\n`;
            ma.desks.forEach(desk => {
                if (desk.persons.length) {
                    msg += `  📊 <b>${desk.name} Masa:</b>\n`;
                    desk.persons.forEach(p => msg += `    • ${p.name}\n`);
                }
            });
            if (ma.makKoyma && ma.makKoyma.length) msg += `  🏗️ Mak.Koyma: ${ma.makKoyma.map(p => p.name).join(', ')}\n`;
            if (ma.etiket.length) msg += `  🏷️ Etiket: ${ma.etiket.map(p => p.name).join(', ')}\n`;
            if (ma.kontrol.length) msg += `  🔍 Kontrol: ${ma.kontrol.map(p => p.name).join(', ')}\n`;
            if (ma.koli.length) msg += `  📦 Koli: ${ma.koli.map(p => p.name).join(', ')}\n`;
            msg += `\n`;
        });

        if (assignment.fixedRoles && assignment.fixedRoles.length) {
            msg += `🪣 <b>Sabit Görevliler:</b>\n`;
            assignment.fixedRoles.forEach(p => msg += `  • ${p.name} → ${p.role === 'teneke' ? 'Teneke Açma' : p.role}\n`);
            msg += `\n`;
        }
        if (assignment.tasks.dilimleme.length) msg += `🧀 <b>Dilimleme:</b> ${assignment.tasks.dilimleme.map(p => p.name).join(', ')}\n`;
        if (assignment.tasks.tarihMakinesi.length) msg += `📅 <b>Tarih Makinesi:</b> ${assignment.tasks.tarihMakinesi.map(p => p.name).join(', ')}\n`;

        if (assignment.tasks.temizlik.length) {
            msg += `\n🧹 <b>Temizlik Görevleri:</b>\n`;
            const cleanByArea = {};
            assignment.tasks.temizlik.forEach(p => { if (!cleanByArea[p.area]) cleanByArea[p.area] = []; cleanByArea[p.area].push(p.name); });
            Object.entries(cleanByArea).forEach(([area, names]) => msg += `  🧹 ${area}: ${names.join(', ')}\n`);
        }
        msg += `\n━━━━━━━━━━━━━━━━━━━━\n`;
        msg += `✅ <i>${isTest ? 'Test' : 'Otomatik'} atama - ${new Date().toLocaleString('tr-TR', { timeZone: 'Europe/Istanbul' })}</i>`;

        await sendTelegram(msg);
        console.log('Tamamlandi!');
    } catch (e) {
        console.error('Hata:', e);
        await sendTelegram('❌ Otomatik atama hatasi: ' + e.message);
    }
}

cron.schedule('0 17 * * 3,6', () => { console.log('Cron:', new Date().toISOString()); runAutoAssign(false); }, { timezone: 'Europe/Istanbul' });

console.log('🤖 Ozisik Paketleme Bot baslatildi');
console.log('⏰ Zamanlama: Her Carsamba ve Cumartesi 17:00 (TR)');

const http = require('http');
http.createServer((req, res) => {
    if (req.url === '/test') {
        runAutoAssign(true);
        res.writeHead(200, {'Content-Type':'text/plain; charset=utf-8'});
        res.end('Test atama tetiklendi - Telegram grubunu kontrol edin');
    } else {
        res.writeHead(200, {'Content-Type':'text/plain; charset=utf-8'});
        res.end('Ozisik Bot aktif | Sonraki otomatik atama: Car/Cmt 17:00');
    }
}).listen(process.env.PORT || 3000, () => console.log('HTTP port', process.env.PORT || 3000));
